update CI

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -31,9 +31,9 @@ jobs:
           - 21
         include:
           - java_version: '17'
-            maven_opts: ''
+            mvn_opts: ''
           - java_version: '21'
-            maven_opts: ''
+            mvn_opts: ''
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -54,17 +54,26 @@ jobs:
           cache: 'maven'
       - name: Compile and test with JDK ${{ matrix.java_version }}
         run: |
-          mvn -B -U -T4C test javadoc:aggregate \
-            -Dgib.disable=false -Dgib.referenceBranch=__branch_before \
-            ${{ matrix.maven_opts }}
+          mvn -B -U -T8C test javadoc:aggregate \
+            ${{ matrix.mvn_opts }}
 
       - name: Integration test with JDK ${{ matrix.java_version }}
-        if: ${{ github.repository == 'langchain4j/langchain4j-community' }}
+        ## allow builds to run only:
+        ## - on the main branch when it is not a pull request,
+        ## - for pull requests from the same repository
+        ## - when triggered manually
+        if: (github.event_name == 'pull_request' && github.head_repo.full_name == github.repository) || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
         run: |
           mvn -B -U verify \
-            -Dtinylog.writer.level=info \
             -Dgib.disable=false -Dgib.referenceBranch=__branch_before \
-            ${{ matrix.maven_opts }}
+            ${{ matrix.mvn_opts }}
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/*-reports/TEST-*.xml'
+          annotate_only: true
 
   # For checking some compliance things (require a recent JDK due to plugins so in a separate step)
   compliance:
